# Generated by Django 3.0 on 2020-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('name3', models.CharField(max_length=200)),
                ('name4', models.CharField(max_length=200)),
                ('court', models.CharField(choices=[('court 1', 'court 1'), ('court 2', 'court 2'), ('court 3', 'court 3'), ('court 4', 'court 4'), ('court 5', 'court 5'), ('court 6', 'court 6'), ('court 7', 'court 7'), ('court 8', 'court 8')], default='Choose your Court', max_length=100)),
                ('time', models.CharField(choices=[('8.00', '8.00'), ('9.00', '9.00'), ('10.00', '10.00'), ('11.00', '11.00'), ('12.00', '12.00'), ('13.00', '13.00'), ('14.00', '14.00'), ('15.00', '15.00'), ('16.00', '16.00'), ('17.00', '17.00'), ('18.00', '18.00'), ('19.00', '19.00'), ('20.00', '20.00'), ('21.00', '21.00')], default='Choose your Time', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ExamScore',
        ),
    ]
