# Generated by Django 3.0 on 2020-12-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201212_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='time',
            name='court',
            field=models.CharField(choices=[('court 1', 'court 1'), ('court 2', 'court 2'), ('court 3', 'court 3'), ('court 4', 'court 4'), ('court 5', 'court 5'), ('court 6', 'court 6'), ('court 7', 'court 7'), ('court 8', 'court 8')], default='court 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(choices=[('8.00', '8.00'), ('9.00', '9.00'), ('10.00', '10.00'), ('11.00', '11.00'), ('12.00', '12.00'), ('13.00', '13.00'), ('14.00', '14.00'), ('15.00', '15.00'), ('16.00', '16.00'), ('17.00', '17.00'), ('18.00', '18.00'), ('19.00', '19.00'), ('20.00', '20.00'), ('21.00', '21.00')], default='8.00', max_length=100),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Branch')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.College')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.College'),
        ),
    ]
