# Generated by Django 3.0 on 2020-12-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20201214_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
